# Generated by Django 6.1.1 on 2026-09-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, verbose_name="Номер / Название кабинета"
                    ),
                ),
                ("floor", models.IntegerField(default=1, verbose_name="Этаж")),
            ],
            options={
                "verbose_name": "Кабинет",
                "verbose_name_plural": "Кабинеты",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="ФИО сотрудника"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Должность"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование техники"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Инвентарный / Серийный номер",
                    ),
                ),
                ("year_manufactured", models.IntegerField(verbose_name="Год выпуска")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_use", "В эксплуатации"),
                            ("in_stock", "На складе"),
                            ("repair", "В ремонте"),
                            ("written_off", "Списано"),
                        ],
                        default="in_use",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "current_cabinet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.cabinet",
                        verbose_name="Текущий кабинет",
                    ),
                ),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.employee",
                        verbose_name="Текущий пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.CreateModel(
            name="EquipmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="assets.equipment",
                        verbose_name="Техника",
                    ),
                ),
                (
                    "new_cabinet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assets.cabinet",
                        verbose_name="Новый кабинет",
                    ),
                ),
                (
                    "new_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assets.employee",
                        verbose_name="Новый пользователь",
                    ),
                ),
                (
                    "old_cabinet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assets.cabinet",
                        verbose_name="Старый кабинет",
                    ),
                ),
                (
                    "old_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assets.employee",
                        verbose_name="Старый пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись истории",
                "verbose_name_plural": "История перемещений",
                "ordering": ["-change_date"],
            },
        ),
    ]
