# Generated by Django 6.1.1 on 2026-09-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("pc", "Компьютер / ПК"),
                    ("laptop", "Ноутбук"),
                    ("monitor", "Монитор"),
                    ("printer", "МФУ / Принтер"),
                    ("other", "Другое оборудование"),
                ],
                default="pc",
                max_length=20,
                verbose_name="Тип техники",
            ),
        ),
    ]
